l_russian:
 CK2DISPLAYNAME: "из Imperator в Crusader Kings II"
 IMPERATOR: "Imperator"
 CK2GAME: "Crusader Kings II"
 CK2FOLDER: "Crusader Kings II Установить каталог"
 CK2FOLDERTIP: "Путь на вашем компьютере, где установлен Crusader Kings II"
 CK2MOD: "Crusader Kings II Мод Каталог"
 CK2MODTIP: "Путь на вашем компьютере, где хранятся моды Crusader Kings II"
 IMPERATORFOLDER: "Imperator Установить каталог"
 IMPERATORFOLDERTIP: "Путь на вашем компьютере, где установлена Imperator"
 IMPERATORMOD: "Imperator Мод Каталог"
 IMPERATORMODTIP: "Путь на вашем компьютере, где Imperator хранит моды"
 IMPERATORFILE: "Путь к исполняемому файлу конвертера"
 IMPERATORFILETIP: "Путь к Converter.jar"
 IMPERATORSAVE: "Путь к сохранению игры Imperator"
 IMPERATORSAVETIP: "Путь к вашей сохраненной игре от Imperator"
