l_english:
 IMPTOCK2DISPLAYNAME: "Imperator to Crusader Kings II"
 IMPERATOR: "Imperator"
 CK2GAME: "Crusader Kings II"
 CK2FOLDER: "Crusader Kings II Install Directory"
 CK2FOLDERTIP: "The path on your computer where Crusader Kings II is installed"
 CK2MOD: "Crusader Kings II Mod Directory"
 CK2MODTIP: "The path on your computer where Crusader Kings II stores mods"
 IMPERATORFOLDER: "Imperator Install Directory"
 IMPERATORFOLDERTIP: "The path on your computer where Imperator is installed"
 IMPERATORMOD: "Imperator Mod Directory"
 IMPERATORMODTIP: "The path on your computer where Imperator stores mods"
 IMPERATORFILE: "Path to the converter executable"
 IMPERATORFILETIP: "Path to Converter.jar"
 IMPERATORSAVE: "Path to the Imperator savegame"
 IMPERATORSAVETIP: "Path to your savegame from Imperator"